### ISSUE TITLE
Your website is down!

### ISSUE THREAD

**Issue by gnu-user** [dimitri/tapoueh.org#1]
Hi,

Your website is one of the best related to PostgreSQL and databases in general, I noticed that for some reason it's no longer accessible and discovered your GitHub repository.

Please try and get it back online if possible, I believe if your CLISP markup website is just static HTML it can be hosted for free on GitHub pages, otherwise I have a server you can host it on free of charge.

Cheers,
Jon

**Comment by dimitri** [comment]
Thanks for your support! I need to get back on making the static website use _relative links_ only then I will be able to host it at GitHub pages.

**Comment by dimitri** [comment]
http://tapoueh.org is back online. Thanks for opening this issue!

**Comment by gnu-user** [comment]
Amazing, thank you. However I've noticed one issue, I can't recall if you had pagination, but there doesn't seem to be any pagination for your main blog page.

For example, if I go to the following URL I can see recent articles, but I cannot navigate to older articles from previous years.

[http://tapoueh.org/blog/index.html](http://tapoueh.org/blog/index.html)

However, from this article, which I had bookmarked (one of the best PostgreSQL GIS articles I've ever read!) you can see there is some navigation to other blog articles in the form of the `/dev/dim/blog/2013/08` at the top left of the page.

[http://tapoueh.org/blog/2013/08/05-earthdistance](http://tapoueh.org/blog/2013/08/05-earthdistance)

**Comment by dimitri** [comment]
Yeah, and there's also the Archives page at http://tapoueh.org/blog/archives.html that I don't know if it's linked somewhere in the site. Been a long time I didn't spend some time with it, maybe I should consider simplifying it a lot when it comes to navigation and theming. I didn't change the way navigation is done tho.

**Comment by gnu-user** [comment]
The archives page works well, if you get some time to simplify navigation a little bit that would help. You definitely have one of the best blogs related to more advanced topics on not just PostgreSQL but SQL in general.

Thanks for getting the site back online!
